# Generated by Django 2.2.6 on 2020-09-20 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 4, 23, 36, 442538, tzinfo=utc), verbose_name='date expired'),
            preserve_default=False,
        ),
    ]
